import { create } from "zustand";
import {
  notificationsByAudience,
  type AppNotification,
  type NotificationAudience,
  type NotificationType,
} from "@/lib/api/notifications";

export interface SystemNotificationInput {
  type: NotificationType;
  title: string;
  body: string;
  entityType?: string;
  entityId?: string;
  action?: string;
  actor?: string;
}

interface NotificationsState {
  audience: NotificationAudience;
  items: AppNotification[];
  /** Point the bell + list at a portal's notifications (called by the shell). */
  setAudience: (audience: NotificationAudience) => void;
  unreadCount: () => number;
  markRead: (id: string) => void;
  markAllRead: () => void;
  /** Prepend a live, unread notification generated by an action (bell +1). */
  pushSystem: (n: SystemNotificationInput) => void;
}

let sysSeq = 0;

const clone = (audience: NotificationAudience) =>
  notificationsByAudience[audience].map((n) => ({ ...n }));

/**
 * Session-scoped notifications shared by the topbar bell + the notifications
 * page. Audience-aware: the app shell calls `setAudience(role)` so an owner sees
 * only owner-relevant notifications, a tenant only theirs, staff the org feed.
 * Read state persists while the audience is unchanged (navigating within a portal).
 */
export const useNotifications = create<NotificationsState>((set, get) => ({
  audience: "admin",
  items: clone("admin"),
  setAudience: (audience) =>
    set((s) => (s.audience === audience ? {} : { audience, items: clone(audience) })),
  unreadCount: () => get().items.filter((n) => n.status !== "read").length,
  markRead: (id) =>
    set((s) => ({
      items: s.items.map((n) =>
        n.id === id ? { ...n, status: "read", read_at: new Date().toISOString() } : n,
      ),
    })),
  markAllRead: () =>
    set((s) => ({
      items: s.items.map((n) => ({
        ...n,
        status: "read" as const,
        read_at: n.read_at ?? new Date().toISOString(),
      })),
    })),
  pushSystem: (n) =>
    set((s) => ({
      items: [
        {
          id: `sys_${++sysSeq}_${Date.now()}`,
          type: n.type,
          title: n.title,
          body: n.body,
          channel: "in_app",
          status: "sent",
          sent_at: new Date().toISOString(),
          read_at: null,
          entityType: n.entityType,
          entityId: n.entityId,
          action: n.action,
          actor: n.actor,
        },
        ...s.items,
      ],
    })),
}));
