import { create } from "zustand";
import {
  notificationsByAudience,
  type AppNotification,
  type NotificationAudience,
  type NotificationType,
} from "@/lib/api/notifications";

export interface SystemNotificationInput {
  type: NotificationType;
  title: string;
  body: string;
  /** Restrict who may see this. Undefined = everyone (the usual case). */
  audiences?: NotificationAudience[];
  entityType?: string;
  entityId?: string;
  action?: string;
  actor?: string;
}

interface NotificationsState {
  audience: NotificationAudience;
  items: AppNotification[];
  /** Notifications raised at runtime by actions. Kept separately so they survive an
   *  audience switch (which re-clones the seeded feed) and can be persisted. */
  systemItems: AppNotification[];
  /** Point the bell + list at a portal's notifications (called by the shell). */
  setAudience: (audience: NotificationAudience) => void;
  unreadCount: () => number;
  markRead: (id: string) => void;
  markAllRead: () => void;
  /** Prepend a live, unread notification generated by an action (bell +1). */
  pushSystem: (n: SystemNotificationInput) => void;
  /** MOCK-LAYER: restore runtime notifications after a hard reload. */
  hydrate: (systemItems: AppNotification[]) => void;
}

let sysSeq = 0;

const clone = (audience: NotificationAudience) =>
  notificationsByAudience[audience].map((n) => ({ ...n }));

/** Runtime notifications visible to one audience. */
const visibleTo = (list: AppNotification[], audience: NotificationAudience) =>
  list.filter((n) => !n.audiences || n.audiences.includes(audience));

const markIn = (list: AppNotification[], id: string) =>
  list.map((n) => (n.id === id ? { ...n, status: "read" as const, read_at: new Date().toISOString() } : n));

const markAllIn = (list: AppNotification[]) =>
  list.map((n) => ({ ...n, status: "read" as const, read_at: n.read_at ?? new Date().toISOString() }));

/**
 * Session notifications shared by the topbar bell + the notifications page.
 * Audience-aware: the app shell calls `setAudience(role)` so an owner sees only
 * owner-relevant notifications, a tenant only theirs, staff the org feed.
 * Runtime notifications (`systemItems`) ride along on every audience so an action
 * taken on the marketing site is still visible after landing in the dashboard —
 * UNLESS they carry an explicit `audiences` restriction. That escape hatch exists
 * because some messages must never reach a particular party: an owner declining a
 * repair gives Nexora a reason that the tenant must not see, since owners and
 * tenants never deal with each other directly in this model.
 */
export const useNotifications = create<NotificationsState>((set, get) => ({
  audience: "admin",
  items: clone("admin"),
  systemItems: [],
  setAudience: (audience) =>
    set((s) =>
      s.audience === audience
        ? {}
        : { audience, items: [...visibleTo(s.systemItems, audience), ...clone(audience)] },
    ),
  unreadCount: () => get().items.filter((n) => n.status !== "read").length,
  markRead: (id) =>
    set((s) => ({ items: markIn(s.items, id), systemItems: markIn(s.systemItems, id) })),
  markAllRead: () =>
    set((s) => ({ items: markAllIn(s.items), systemItems: markAllIn(s.systemItems) })),
  pushSystem: (n) =>
    set((s) => {
      const entry: AppNotification = {
        id: `sys_${++sysSeq}_${Date.now()}`,
        type: n.type,
        title: n.title,
        body: n.body,
        channel: "in_app",
        status: "sent",
        sent_at: new Date().toISOString(),
        read_at: null,
        entityType: n.entityType,
        entityId: n.entityId,
        action: n.action,
        actor: n.actor,
        audiences: n.audiences,
      };
      // Only surface it in the live list if the current audience is allowed to see it.
      const visible = !entry.audiences || entry.audiences.includes(s.audience);
      return {
        items: visible ? [entry, ...s.items] : s.items,
        systemItems: [entry, ...s.systemItems],
      };
    }),
  hydrate: (systemItems) =>
    set((s) => {
      if (systemItems.length === 0) return {};
      const seeded = s.items.filter((n) => !n.id.startsWith("sys_"));
      return { systemItems, items: [...visibleTo(systemItems, s.audience), ...seeded] };
    }),
}));
